Feature/14 implement review domain
xandervedder/BEP-03 pull request #27
Opened 2021-12-01 11:32 UTC by xandervedder

## Changes
Add a few domain classes that will eventually make it possible to save reviews.

## Checklist
- [ ] Add `Review` class with unit tests
- [ ] Format all modified files
- [ ] Check for missing newlines

## When merging, this pull request 
closes #14

2021-12-01 13:01 UTC, Rubenvdbrink commented on review/src/main/java/nl/softwarestrijders/waiter/review/core/domain/Review.java
> +    private static final int MAX_DESCRIPTION_LENGTH = 256; // Is this not enough? Should it be more?
I would say 512 characters

2021-12-01 13:24 UTC, JustMilan commented
Why use a .gitkeep to keep the application folder if it's not being used?

2021-12-01 13:30 UTC, xandervedder commented
> Why use a .gitkeep to keep the application folder if it's not being used?

So I don't have to create the folder again 🧠

2021-12-01 13:48 UTC, JustMilan requested changes

2021-12-01 13:48 UTC, JustMilan commented on review/src/main/java/nl/softwarestrijders/waiter/review/core/domain/Review.java
> +     * @param customerId The id of the customer.
nit: Here, you are using a capital letter after the param name while you're using non capital letters in other @param

2021-12-01 13:48 UTC, JustMilan commented on review/src/main/java/nl/softwarestrijders/waiter/review/core/domain/Review.java
> +     * @param customerId The id of the customer.
There are multiple occasions where this happens.

2021-12-01 13:49 UTC, JustMilan commented on review/src/main/java/nl/softwarestrijders/waiter/review/core/domain/Review.java
> +     * @param customerId The id of the customer.
If you don't see this as any sort of problem, just resolve this.

2021-12-01 13:58 UTC, Rubenvdbrink submitted a review, later dismissed
LGTM

2021-12-01 15:17 UTC, JustMilan requested changes
Please change PR title as you've said here
https://discord.com/channels/679327408343613460/684494959054684236/915365806479638528

2021-12-01 15:43 UTC, xandervedder commented on review/src/main/java/nl/softwarestrijders/waiter/review/core/domain/Review.java
> +     * @param customerId The id of the customer.
Should be consistent now

2021-12-01 15:56 UTC, xandervedder commented
Not done yet, I have differentiate between a product and delivery review i.e. i need the product id or delivery id... will continue working on this a bit later

2021-12-02 16:47 UTC, Rubenvdbrink approved these changes
👀✅2me

2021-12-02 18:15 UTC, JustMilan approved these changes

2021-12-02 18:16 UTC, merged