Feature/17 create order domain
xandervedder/BEP-03 pull request #30
Opened 2021-12-01 12:55 UTC by JortWillemsen

## Changes
A short description about the overall changes you've made to the project.

## Checklist
- [ ] Implement XYZ
- [ ] Add tests
- [ ] Format all modified files
- [ ] Check for missing newlines
- [ ] ...

## When merging, this pull request 
closes #

2021-12-01 13:56 UTC, JustMilan requested changes

2021-12-01 13:56 UTC, JustMilan commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/Order.java
> +    // TODO: Write tests for this method.
Remove TODO's

2021-12-01 13:56 UTC, JustMilan commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/Price.java
> +    private double vat = 0.21f;
Isn't this a magic number? Maybe make it a constant somewhere or a static final?

2021-12-01 13:56 UTC, JustMilan commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/Price.java
> +        return new Price();
Just a check, is this correct?

2021-12-01 13:56 UTC, JustMilan commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/Receipt.java
> +    //TODO: Generate new id for each receipt item
Remove or resolve TODO's please.

2021-12-01 13:56 UTC, JustMilan commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/ReceiptItem.java
> +        }
Maybe remove the braces from the if statement as you do it everywhere else.

2021-12-01 13:56 UTC, JustMilan commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/id/DeliveryId.java
> +
Is this linebreak intentional?

2021-12-01 13:56 UTC, JustMilan commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/id/OrderId.java
> +
Is this linebreak intentional? (As you don't have it in the ProductId.java for example)

2021-12-01 13:57 UTC, JustMilan commented
Please complete the closes keyword

2021-12-01 13:59 UTC, JustMilan requested changes
Rename PR as @xandervedder explained here https://discord.com/channels/679327408343613460/684494959054684236/915365806479638528

2021-12-01 13:59 UTC, JustMilan requested changes
Please complete the closes keyword

2021-12-01 14:00 UTC, JustMilan requested changes
Please fix code smells.
https://sonarcloud.io/project/issues?id=nl.softwarestrijders.waiter%3Aorder&pullRequest=30&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL

2021-12-01 16:10 UTC, xandervedder requested changes
Nitpicks, changes...  I have all of them for you :smile: 

Biggest thing: use records :+1:

2021-12-02 19:31 UTC, xandervedder commented on order/src/main/java/nl/softwarestrijders/waiter/order/common/annotation/TestExcludeGenerated.java
> +}
Figured out what this does, its some magic naming thing from JaCoCo, Also the name can simply be `Generated`, that works too :)

2021-12-02 21:11 UTC, JortWillemsen commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/Price.java
> +        return new Price();
This is indeed work in progress. My plan is that this function will somehow check the prices of products by accessing the product service and returning a Price object which holds a subtotal and total and the VAT by which it is calculated.

2021-12-02 21:13 UTC, JortWillemsen commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/Price.java
> +    private double vat = 0.21f;
I insert this value in the constructor because VAT can change (food and beverages are 9%, other things are 21%. and that is just in the Netherlands). The 21% is just the default value that will be used when nothing is given in the constructor.

2021-12-02 21:14 UTC, JortWillemsen commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/Order.java
> +    // TODO: Write tests for this method.
Yep. I just need the product service for this function to work.

2021-12-02 21:39 UTC, JustMilan commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/Price.java
> +    private double vat = 0.21f;
Maybe using @xandervedder his solution in combination with yours if a good solution?

Otherwise you can just resolve this conversation

2021-12-03 08:21 UTC, xandervedder commented on order/src/main/java/nl/softwarestrijders/waiter/order/domain/Receipt.java
> +        var item = this.items.stream().filter(i -> i.getProductId().id().equals(id.id())).findFirst();
You're using records, equals is generated for you :smile: 
```suggestion
        var item = this.items.stream().filter(i -> i.getProductId().equals(id)).findFirst();
```

2021-12-03 10:47 UTC, JustMilan approved these changes

2021-12-04 11:02 UTC, xandervedder commented on order/src/test/java/nl/softwarestrijders/waiter/order/domain/OrderTest.java
> +    }
@JortWillemsen did you take a look at this?

2021-12-06 08:04 UTC, xandervedder commented on order/src/test/java/nl/softwarestrijders/waiter/order/domain/OrderTest.java
> +    }
He did, he doesn't want to do it :disappointed:

2021-12-06 08:05 UTC, xandervedder approved these changes

2021-12-06 08:05 UTC, merged