Feature/9 customer setup mongodb
xandervedder/BEP-03 pull request #31
Opened 2021-12-01 17:34 UTC by JustMilan

## Changes
A short description about the overall changes you've made to the project.

## Checklist
- [X] Implement MongoDB
- [X] Add/edit tests
- [X] Format all modified files
- [X] Check for missing newlines
- [X] Add repositories
- [X] Add Document annotations

## When merging, this pull request 
closes #9

2021-12-01 18:25 UTC, xandervedder requested changes

2021-12-01 18:25 UTC, xandervedder commented on customer/src/test/java/nl/softwarestrijders/waiter/customer/core/domain/CustomerTest.java
> +		assertDoesNotThrow(() -> customer.setId(new UUID(1, 1)));
might wanna make this UUID in the constructor of the customer, btw `UUID.createRandomUUID()` (static method) is preferred

2021-12-01 19:36 UTC, JustMilan commented on customer/src/test/java/nl/softwarestrijders/waiter/customer/core/domain/CustomerTest.java
> +		assertDoesNotThrow(() -> customer.setId(new UUID(1, 1)));
Good one, was questioning myself to do so

2021-12-02 19:16 UTC, Rubenvdbrink approved these changes
👀✅2me

2021-12-02 19:16 UTC, Rubenvdbrink commented
![image](https://user-images.githubusercontent.com/60598779/144488118-4e863ffe-5139-49f7-9122-87bedbc3f04c.png)

2021-12-02 19:26 UTC, xandervedder approved these changes
You should probably think about using `UUID.randomUUID()` in the constructor of both of your domain classes, but that can be done later.

2021-12-02 19:26 UTC, merged