Add domain for the product micro-service
xandervedder/BEP-03 pull request #32
Opened 2021-12-01 21:03 UTC by Rubenvdbrink

## Changes
Added domain and tests for Product Micro-Service

## Checklist
- [ ] Make domain
- [ ] Make tests
- [ ] add jacoco to pom

## When merging, this pull request 
closes #27

2021-12-01 22:05 UTC, JustMilan requested changes

2021-12-01 22:05 UTC, JustMilan commented on product/src/main/java/nl/softwarestrijders/waiter/product/domain/Product.java
> +        Objects.requireNonNull(nutritionalValue, "The product needs to have nutritional values");
Maybe check for Empty too?
requireNonBlankOrEmpty(nutririonalValue);

2021-12-02 16:38 UTC, Rubenvdbrink commented on product/src/main/java/nl/softwarestrijders/waiter/product/domain/Product.java
> +        Objects.requireNonNull(nutritionalValue, "The product needs to have nutritional values");
Nutritional Value can't be emtpy, this is already checked in the Nutritional Value constructor

2021-12-02 19:12 UTC, xandervedder commented on product/src/main/java/nl/softwarestrijders/waiter/product/common/Generated.java
> +}
F.Y.I. the reason this works;
> Classes and methods annotated with annotation whose retention policy is runtime or class and whose simple name is Generated are filtered out during generation of report - JaCoCo

In my opinion it pollutes the codebase a little bit, but alrighty

2021-12-02 19:16 UTC, xandervedder requested changes

2021-12-02 19:16 UTC, xandervedder commented on product/src/main/java/nl/softwarestrijders/waiter/product/domain/NutritionalValue.java
> +            if(value < 0) throw new IllegalArgumentException("Nutritional value has to be bigger than 0.");
nit:
```suggestion
        for (var value : List.of(kcal, fats, carbs, proteins, salts))
            if (value < 0) throw new IllegalArgumentException("Nutritional value has to be bigger than 0.");
```

2021-12-02 19:16 UTC, xandervedder commented on product/src/main/java/nl/softwarestrijders/waiter/product/domain/Product.java
> +    public int getWeight() {return weight;}
Personally (this is why linting is kinda nice.. I blame myself) I would format with intellij, and see what comes out of it.

2021-12-02 19:16 UTC, xandervedder commented on product/src/test/java/nl/softwarestrijders/waiter/product/domain/NutritionalValueTest.java
> +                Arguments.of(-1,-1,-1,-1,-1)
nit:
```suggestion
                Arguments.of(-1, 0, 0, 0, 0),
                Arguments.of(0, -1, 0, 0, 0),
                Arguments.of(0, 0, -1, 0, 0),
                Arguments.of(0, 0, 0, -1, 0),
                Arguments.of(0, 0, 0, 0, -1),
                Arguments.of(-1, -1, -1, -1, -1)
```

2021-12-02 19:16 UTC, xandervedder commented on product/src/test/java/nl/softwarestrijders/waiter/product/domain/NutritionalValueTest.java
> +                Arguments.of(100,100,100,100,100)
nit: same as above

2021-12-02 19:20 UTC, Rubenvdbrink commented on product/src/main/java/nl/softwarestrijders/waiter/product/domain/Product.java
> +    public int getWeight() {return weight;}
`    @Generated
    public UUID getId() {
        return id;
    }

    @Generated
    public double getPrice() {
        return price;
    }

    @Generated
    public String getDescription() {
        return description;
    }

    @Generated
    public String getName() {
        return name;
    }

    @Generated
    public NutritionalValue getNutritionalValue() {
        return nutritionalValue;
    }

    @Generated
    public int getWeight() {
        return weight;
    }`

2021-12-02 19:21 UTC, JustMilan approved these changes

2021-12-02 19:28 UTC, xandervedder commented on product/src/main/java/nl/softwarestrijders/waiter/product/domain/Product.java
> +    public int getWeight() {return weight;}
Yes those are collapsed, are they not? if you expand them they would look like this, right:
```java
    @Generated
    public String getName() {
        return name;
    }
```

2021-12-02 19:30 UTC, xandervedder approved these changes

2021-12-02 19:30 UTC, merged