Feature/22 delivery domain
xandervedder/BEP-03 pull request #35
Opened 2021-12-05 11:54 UTC by arjennorbart

## Changes
First implementation of the Delivery service domain

## Checklist
- [ ] Implement DeliveryAddress and Delivery Class.
- [ ] Add tests
- [ ] Format all modified files
- [ ] Check for missing newlines

## When merging, this pull request 
closes #22 
closes #24

2021-12-05 12:10 UTC, xandervedder requested changes

2021-12-05 12:10 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/Delivery.java
> +    private final UUID orderId;
The `final` modifier can cause issues with MongoDb, I am assuming that this hasn't been tested yet

2021-12-05 12:10 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/Delivery.java
> +        this.orderId = orderId;
You're doing duplicate things here, it would be better to just use the setters in here and leaving all the other logic in the setter

```suggestion
        Objects.requireNonNull(orderId, "Cannot make a delivery without an order reference");
        this.orderId = orderId;
        
        this.setStatus(status);
```

2021-12-05 12:10 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/DeliveryAddress.java
> +    }
This is unnecessary, as a Record already generates these for you:
https://docs.oracle.com/en/java/javase/14/language/records.html
```suggestion
```

2021-12-05 12:10 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/Status.java
> +    FAILED //Delivery failed (something went wrong)
nit:
```suggestion
    REGISTERED, // REQUESTED
    INPICKUP, // Courier is on his way to pick up the order
    PICKUP, // Courier arrived at the restaurant for the pick up
    CONVEYING, // Courier is under way
    DELIVERED, // Courier delivered the order
    DELAYED, // Delivery got delayed
    FAILED // Delivery failed (something went wrong)
```

2021-12-05 12:10 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/Delivery.java
> +        }
```suggestion
        this.status = switch (this.status) {
            case DELIVERED, FAILED -> throw new InvalidStatusUpdateException();
            default -> yield status;
        }
```

https://docs.oracle.com/en/java/javase/13/language/switch-expressions.html

2021-12-05 12:26 UTC, arjennorbart commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/DeliveryAddress.java
> +    }
Did this for Jacoco coverage

2021-12-05 12:34 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/DeliveryAddress.java
> +    }
I would personally just add a test that checks if the right value is retrieved, I think that this is polluting your codebase unnecessarily.

2021-12-05 14:58 UTC, arjennorbart commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/Delivery.java
> +        }
What you suggest doesn't work. Also the way I do it is in the documentation link. Not sure what difference it would make changing this?

2021-12-05 15:19 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/Delivery.java
> +        }
Ah check, `yield` is only used when you have an actual block: `{ ... }`

It should be
```suggestion
        this.status = switch (this.status) {
            case DELIVERED, FAILED -> throw new InvalidStatusUpdateException();
            default -> status;
        }
```

> Not sure what difference it would make changing this?

It makes it clear what you're trying to do

2021-12-06 08:16 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/Status.java
> +    FAILED // Delivery failed (something went wrong)
nit: trailing comma
```suggestion
    FAILED, // Delivery failed (something went wrong)
```

2021-12-06 08:16 UTC, JustMilan approved these changes

2021-12-06 08:25 UTC, JustMilan commented
https://sonarcloud.io/project/issues?id=nl.softwarestrijders.waiter%3Adelivery&pullRequest=35&resolved=false&types=CODE_SMELL

There are 7 code smells.

2021-12-06 08:47 UTC, JortWillemsen requested changes

2021-12-06 08:47 UTC, JortWillemsen commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/Delivery.java
> +            this.status = status;
```suggestion
```

You could also remove this if statement entirely since it will be handled by the switch statement.
The default of the switch will be triggered when `this.status` is null and therefor yield the same results.

2021-12-06 08:47 UTC, JortWillemsen commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/DeliveryAddress.java
> +        Objects.requireNonNull(streetName);
```suggestion
        Objects.requireNonNull(streetName, "Need a valid street name to create a new address");
```

You could write a description for this exception throw like you do in other cases where you use `Objects.requireNonNull()`

2021-12-06 08:47 UTC, JortWillemsen commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/DeliveryAddress.java
> +        Objects.requireNonNull(city);
```suggestion
        Objects.requireNonNull(city, "Need a valid city to create a new address");
```

You could write a description for this exception throw like you do in other cases where you use Objects.requireNonNull()

2021-12-06 09:05 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/domain/Delivery.java
> +        }
```suggestion
        if (this.status == DELIVERED || this.status == FAILED)
            throw new InvalidStatusUpdateException();
            
        this.status = Objects.requireNonNull(status, "Need a valid status to set or update");;
```

2021-12-06 12:12 UTC, arjennorbart commented
> https://sonarcloud.io/project/issues?id=nl.softwarestrijders.waiter%3Adelivery&pullRequest=35&resolved=false&types=CODE_SMELL
> 
> There are 7 code smells.

fixed:

![image](https://user-images.githubusercontent.com/57788003/144843928-3d76af6f-7763-4b3d-afea-7cacaf44ffc2.png)

2021-12-06 13:01 UTC, Rubenvdbrink approved these changes
LGTM

2021-12-06 13:07 UTC, xandervedder approved these changes

2021-12-06 13:08 UTC, merged