Setup CQRS for customer microservice
xandervedder/BEP-03 pull request #60
Opened 2021-12-15 23:44 UTC by JustMilan

## Changes
A short description about the overall changes you've made to the project.

## Checklist
- [ ] Implement commands
- [ ] Implement queries
- [ ] Format all modified files
- [ ] Check for missing newlines

## When merging, this pull request 
closes #12

2021-12-16 00:00 UTC, xandervedder requested changes
Some nits and stuff

2021-12-16 00:37 UTC, JustMilan commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/application/CustomerCommandHandler.java
> +	public Customer findCustomerById(UUID id) {
Please resolve if you think I've resolved it correclty.

2021-12-16 00:37 UTC, JustMilan commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/application/CustomerQueryHandler.java
> +	}
Please resolve if you think I've resolved it correclty.

2021-12-16 00:37 UTC, JustMilan commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/application/query/GetAddressByCustomerId.java
> +
Please resolve if you think I've resolved it correclty.

2021-12-16 00:37 UTC, JustMilan commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/domain/Customer.java
> +	private List<UUID> reviews;
Please resolve if you think I've resolved it correclty.

2021-12-16 00:37 UTC, JustMilan commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/domain/Customer.java
> +		return events;
Please resolve if you think I've resolved it correclty.

2021-12-16 00:37 UTC, JustMilan commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/domain/event/AddOrderToCustomer.java
> +}
Please resolve if you think I've resolved it correclty.

2021-12-16 00:37 UTC, JustMilan commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/infrastructure/driver/messaging/RabbitMqEventListener.java
> +			case "customer.review.removed" -> this.commandHandler.handleReviewRemoved(customerId, reviewId);
Please resolve if you think I've resolved it correclty.

2021-12-16 11:06 UTC, xandervedder commented on customer/pom.xml
> +			**/application/exception/*.*,
```suggestion
                        **/application/**,
                        **/domain/event/**,
                        **/infrastructure/**,
```

should do the trick, too

2021-12-16 11:12 UTC, xandervedder requested changes

2021-12-16 11:12 UTC, xandervedder commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/domain/event/ReviewAddedToCustomerEvent.java
> +	}
I only meant the naming scheme, this is wrong, since this would route back to your service (and that's not what you want).

this event will be published so it would have to go to my service (https://github.com/xandervedder/BEP-03/tree/master/review#routing-key)

2021-12-16 11:13 UTC, xandervedder commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/domain/event/AddOrderToCustomer.java
> +}
I always do that :)

2021-12-16 13:00 UTC, xandervedder commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/infrastructure/driver/messaging/RabbitMqEventListener.java
> +	public void listen(ReviewEvent event) {
your application doesn't start (atleast, when I try it) since the properties don't exist

2021-12-16 13:02 UTC, xandervedder commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/infrastructure/driver/messaging/RabbitMqEventListener.java
> +	public void listen(ReviewEvent event) {
> Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'messaging.queue.customer.product' in value "#{'${messaging.queue.customer.product}'}"

2021-12-16 13:05 UTC, xandervedder commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/infrastructure/driver/messaging/RabbitMqEventListener.java
> +	public void listen(ReviewEvent event) {
And you haven't configured all the other queues yet, so that's not gonna work either

2021-12-17 09:10 UTC, xandervedder commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/domain/Customer.java
>   * Class containing {@link Customer} data like first name, last name and email.
`@Document(collection = "customer")`, same for Address

2021-12-20 11:34 UTC, xandervedder approved these changes

2021-12-20 11:38 UTC, Rubenvdbrink commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/application/query/GetEmailAddressFromCustomer.java
> +
remove whiteline for consistency

2021-12-20 11:39 UTC, Rubenvdbrink approved these changes

2021-12-20 11:40 UTC, merged