Feature/69 nice controller and cqrs product service
xandervedder/BEP-03 pull request #71
Opened 2021-12-19 14:26 UTC by Rubenvdbrink

## Changes
A short description about the overall changes you've made to the project.

## Checklist
- [ ] configured rabbitmq correctly with the last up-to-date way (not sure if we're still gonna change the naming scheme but we will discuss that on 20/12/2021)
- [ ] Add add product, delete product commands
- [ ] Add get product by id query

## When merging, this pull request 
closes #29 #45 #69 (nice) #44 #70

2021-12-19 14:42 UTC, xandervedder submitted a review, later dismissed

2021-12-19 14:42 UTC, xandervedder commented on product/src/main/java/nl/softwarestrijders/waiter/product/infrastructure/driver/web/ProductDto.java
> +}
nit: inconsistent formatting with the other records (e.g. `CreateProductEvent`)

2021-12-19 14:42 UTC, xandervedder commented on product/src/main/java/nl/softwarestrijders/waiter/product/core/port/data/ProductRepository.java
> +}
nit: newline

2021-12-19 16:15 UTC, JustMilan requested changes

2021-12-19 16:15 UTC, JustMilan commented on product/src/main/java/nl/softwarestrijders/waiter/product/core/application/QueryHandler.java
> +                .orElseThrow(() -> new ProductNotFoundException(id));
nit: the `var id = query.id();` is inconsistent with other methods. In other methods you do this inline.
See CommandHandler line 41 for example

If you don't see a problem here, just resolve it.

2021-12-19 16:15 UTC, JustMilan commented on product/src/main/java/nl/softwarestrijders/waiter/product/core/port/data/ProductRepository.java
> +}
yep

2021-12-19 17:14 UTC, xandervedder commented on product/src/main/java/nl/softwarestrijders/waiter/product/core/application/QueryHandler.java
> +                .orElseThrow(() -> new ProductNotFoundException(id));
I don't see how that's relevant? `id` is reused multiple times here, hence it makes sense to put it in a variable. This is not the case for `CommandHandler::41`.

2021-12-20 09:57 UTC, JustMilan submitted a review, later dismissed

2021-12-20 12:32 UTC, xandervedder commented on product/src/main/java/nl/softwarestrijders/waiter/product/infrastructure/driver/web/ProductController.java
> +    public void deleteProduct(@PathVariable String id) {
`/delete/{id}`

2021-12-20 13:31 UTC, xandervedder approved these changes

2021-12-20 14:01 UTC, arjennorbart approved these changes

2021-12-20 14:02 UTC, merged