Feature/23 controllers delivery service
xandervedder/BEP-03 pull request #72
Opened 2021-12-19 17:41 UTC by arjennorbart

## Changes
DO NOT MERGE!
This is a draft. Waiting for order and customer service to provide the necessary events/enpoints.

Feel free to check  it out though!

## Checklist
- [ ] Implement delivery controller
- [ ] Add Customer gateway (HttpCustomerRepository) for getting a delivery address from the customer service by REST
- [ ] Change Listener to listen to the order queue (Needs to be implemented by the order service, no events are published to the queue at the moment).
- [ ] Make command that is used by Listener and will request the delivery address form customer service (need correct endpoint in customer service for this to work)
- [ ] Test everything once required events/endpoints are provided

## When merging, this pull request 
closes #23

2021-12-20 11:16 UTC, JustMilan requested changes
Please rename PR to be more descriptive

2021-12-20 22:57 UTC, xandervedder requested changes

2021-12-20 22:57 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/application/DeliveryCommandHandler.java
> +                customerDeliveryAddress.city());
nit:
```suggestion
        var address = new DeliveryAddress(
                customerDeliveryAddress.street(),
                customerDeliveryAddress.houseNumber(),
                customerDeliveryAddress.addition(),
                customerDeliveryAddress.postalCode(),
                customerDeliveryAddress.city()
         );
```

2021-12-20 22:57 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/application/DeliveryCommandHandler.java
> +    public void handleDeliveryAddressChange(UUID id, DeliveryAddress address) {
👍

2021-12-20 22:57 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/core/port/storage/CustomerRepository.java
> +    CustomerDeliveryAddress getCustomerDeliveryAddress(UUID orderId);
Shouldn't it be `deliveryId` or `customerId`? or am i missing something here

2021-12-20 22:57 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/infrastructure/config/HttpClientConfig.java
> +    private String rootPath;
👍

2021-12-20 22:57 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/infrastructure/config/RabbitMqConfig.java
> +    private String orderRoutingKey;
Could also make properties for these

2021-12-20 22:57 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/infrastructure/driven/storage/CustomerDeliveryAddress.java
> +}
nit:
```suggestion
public record CustomerDeliveryAddress(
        UUID id,
        int houseNumber,
        String addition,
        String street,
        String postalCode,
        String city
) {
}
```

2021-12-20 22:57 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/infrastructure/driven/storage/HttpCustomerRepository.java
> +    //Need to discuss with Milan what call to make to get the Customer and eventually the CustomerDeliveryAddress.
nit:
```suggestion
    // TODO: Need to discuss with Milan what call to make to get the Customer and eventually the CustomerDeliveryAddress.
```

2021-12-20 22:57 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/infrastructure/driven/storage/HttpCustomerRepository.java
> +        var uri = URI.create(this.rootPath + "/customer/order?order=" + orderId);
maybe
```suggestion
        var uri = URI.create(String.format("%s/customer/order?order=%s", this.roothPath, orderId);
```

also, shouldn't it be `rootpath/customer/order/uuid`?

2021-12-20 22:57 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/infrastructure/driver/messaging/RabbitMqEventListener.java
> +        if ("order.created".equals(event.eventKey)) {
nit: i would reverse these

2021-12-20 22:57 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/infrastructure/driver/web/DeliveryController.java
> +    @GetMapping("/status/{id}")
```suggestion
    @GetMapping("{id}/retrieve-status")
```
you can check the slides about combining REST with CQRS

2021-12-21 13:51 UTC, xandervedder approved these changes

2021-12-21 13:52 UTC, JustMilan approved these changes

2021-12-21 13:52 UTC, merged