Feature/85/test integration
xandervedder/BEP-03 pull request #93
Opened 2021-12-21 19:19 UTC by xandervedder

## Changes
A short description about the overall changes you've made to the project.

## Checklist
- [x] Fixed integration between Customer and Review
- [x] Fixed integration between Order, Customer and Review
- [ ] Check if there are more integrations that need to be tested

## When merging, this pull request 
closes #85

2021-12-21 20:42 UTC, JustMilan requested changes

2021-12-21 20:42 UTC, JustMilan commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/infrastructure/driver/messaging/RabbitMqEventListener.java
> +        // TODO: delivery should be deleted when an order is deleted, no?
Shouldn't this be resolved before merge?

2021-12-21 23:28 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/infrastructure/driver/messaging/RabbitMqEventListener.java
> +        // TODO: delivery should be deleted when an order is deleted, no?
Ideally, yes, but this is still a draft. Might implement this tommorow or not

2021-12-22 14:16 UTC, xandervedder commented on delivery/src/main/java/nl/softwarestrijders/waiter/delivery/infrastructure/driver/messaging/RabbitMqEventListener.java
> +        // TODO: delivery should be deleted when an order is deleted, no?
This is implemented now

2021-12-23 11:42 UTC, Rubenvdbrink approved these changes
lgtm, sonarcloud detected some things in delivery tho, not sure if u already noticed.

2021-12-23 11:47 UTC, xandervedder commented
> lgtm, sonarcloud detected some things in delivery tho, not sure if u already noticed.

I did, might fix this

dont merge yet tho

2021-12-23 14:37 UTC, xandervedder commented
> lgtm, sonarcloud detected some things in delivery tho, not sure if u already noticed.

This is fixed now

2021-12-23 16:41 UTC, JustMilan approved these changes

2021-12-23 16:43 UTC, arjennorbart approved these changes

2021-12-23 16:44 UTC, xandervedder commented
Waiting for @Rubenvdbrink

2021-12-23 16:51 UTC, Rubenvdbrink approved these changes
3 small things but good enough

2021-12-23 16:51 UTC, Rubenvdbrink commented on customer/postman/customer-micro-service.postman_collection.json
> +}
newline

2021-12-23 16:51 UTC, Rubenvdbrink commented on customer/src/main/java/nl/softwarestrijders/waiter/customer/core/domain/Customer.java
> +				.orElseThrow(() -> new RuntimeException("No review found"));
custom exception?

2021-12-23 16:51 UTC, Rubenvdbrink commented on review/src/main/java/nl/softwarestrijders/waiter/review/core/application/CommandHandler.java
> +            throw new IllegalArgumentException(String.format("Customer with id %s does not exist", customer));
custom exception?

2021-12-23 16:59 UTC, Rubenvdbrink commented
just merge it @xandervedder

2021-12-23 17:00 UTC, merged